name: Hola Mundo

on: [push]

jobs:
  sayHello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno

    steps:
    - name: Test
      run: echo "Valor ${{ vars.MY_VARIABLE_2 }}"

    - name: Secrets
      run: echo "Secrets ${{ secrets.MY_SECRET }}"

