name: Hola Mundo

on: [push]

jobs:
  sayHello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno

    steps:
    - name: Test
      env: MY_VAR_STEP: Variable a nivel step
      run: echo "Valor $MY_VAR_STEP"

